{"name": "test_exception_handling", "status": "passed", "description": "测试异常处理功能", "steps": [{"name": "测试设置: TestAllureBasic.test_exception_handling", "status": "passed", "start": 1754200617600, "stop": 1754200617604}, {"name": "准备异常测试", "status": "passed", "attachments": [{"name": "异常测试数据", "source": "5bacd811-0c92-4a23-860e-f3d43f79aba9-attachment.json", "type": "application/json"}], "start": 1754200617607, "stop": 1754200617608}, {"name": "执行可能异常的操作", "status": "passed", "attachments": [{"name": "除零异常", "source": "430e5458-fa40-4780-a1b4-b17f1be75916-attachment.json", "type": "application/json"}, {"name": "异常处理结果", "source": "562549bc-ddf2-4811-bbfc-b117a1256614-attachment.txt", "type": "text/plain"}], "start": 1754200617608, "stop": 1754200617613}, {"name": "测试清理: TestAllureBasic.test_exception_handling", "status": "passed", "start": 1754200617616, "stop": 1754200617620}], "attachments": [{"name": "log", "source": "60e1872c-133b-4dc2-8d5e-60a620ec14a7-attachment.txt", "type": "text/plain"}], "start": 1754200617606, "stop": 1754200617614, "uuid": "1b9e87d8-a8e1-4980-8dbb-4edb498f622c", "historyId": "e76a1789503526515afa51c6fc5c59c1", "testCaseId": "e76a1789503526515afa51c6fc5c59c1", "fullName": "testcase.test_allure_basic.TestAllureBasic#test_exception_handling", "labels": [{"name": "feature", "value": "异常处理"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "异常捕获测试"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_allure_basic"}, {"name": "subSuite", "value": "TestAllureBasic"}, {"name": "host", "value": "Ly0217"}, {"name": "thread", "value": "231192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_allure_basic"}], "titlePath": ["testcase", "test_allure_basic.py", "TestAllureBasic"]}