INFO     project_logger:log.py:46 开始测试: TestChatGatewayWithDynamicData.test_chat_gateway_with_mixed_data
ERROR    project_logger:log.py:49 MySQL连接失败: (2003, "Can't connect to MySQL server on '8.133.246.113' (timed out)")
INFO     project_logger:log.py:46 成功创建数据库连接: redis_test
ERROR    project_logger:log.py:49 获取Redis数据失败: Timeout connecting to server
INFO     project_logger:log.py:46 慢速测试警告: TestChatGatewayWithDynamicData.test_chat_gateway_with_mixed_data 耗时 103.14秒
INFO     project_logger:log.py:46 测试完成: TestChatGatewayWithDynamicData.test_chat_gateway_with_mixed_data, 耗时: 103.14秒